files: \.py$
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry check
        description:
          Validates the content of the pyproject.toml file and its consistency
          with the poetry.lock file.
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
