default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        files: \.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      # Use isort for sorting imports.
      - id: isort
        additional_dependencies: ["toml"]
        files: \.py$
  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry check
        description:
          Validates the content of the pyproject.toml file and its consistency
          with the poetry.lock file.
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
