name: Build and release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Poetry publish
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
          poetry publish --build

      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
