name: lint

on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Pre Commit
        uses: pre-commit/action@v2.0.3
